### ISSUE TITLE
Spacing in dist files is incorrect and rendered in pixels

### ISSUE THREAD

**Issue by camslice** [rishabh-rajgarhia/bootstrap-4-utilities#4]
Hi there, nice back port! Finding it very useful on a couple of projects that are stuck in BS3.

I noticed that both `/dist/bs4-utilities-for-bs3.css` and `/dist/bs4-utilities-for-bs3.css.min` have some odd spacing.

```
*-1 = 5px
*-2 = 10px
*-3 = 12px
*-4 = 16px
```

According to the docs: https://getbootstrap.com/docs/4.0/utilities/spacing/ the default should be:

```
*-1 = 0.25rem
*-2 = 0.5rem
*-3 = 1rem
*-4 = 1.5rem
*-5 = 3rem
```

Your `variables.less` file seems to be correct, with `@spacer-default: 1rem`

Are the odd spacing sizes and use of pixel units somehow intentional?

Thanks, Cam

**Comment by camslice** [comment]
Sorry, wrong library :/

Was referring to this one if you're interested: https://github.com/jbarreiros/bs4-utilities-for-bs3

**Comment by rishabh-rajgarhia** [comment]
No worries  😄
